# Generated by Django 2.1 on 2018-08-09 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180809_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caixa',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='preco',
            old_name='author',
            new_name='autor',
        ),
    ]
